modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/FloofHips/TheBeyond/issues"
[[mods]]
modId="the_beyond"
version="${file.jarVersion}"
displayName="The Beyond"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants"
description='''

'''

[[dependencies.thebeyond]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thebeyond]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
